export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS';
export const USERINFO_FAILURE = 'USERINFO_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const CHANGE_COMMUNITY = 'CHANGE_COMMUNITY';
export const SET_TRUENAME = 'SET_TRUENAME';
export const SET_PHONE = 'SET_PHONE';
export const UPDATE_USER_INTERGRAL = 'UPDATE_USER_INTERGRAL';

export const SAVE_NEWSID = 'SAVE_NEWSID';
export const SAVE_NICESID = 'SAVE_NICESID';

export const SAVE_NICE_EDIT = 'SAVE_NICE_EDIT';
export const CLEAR_NICE_EDIT = 'CLEAR_NICE_EDIT';

export const SAVE_MERCHANT = 'SAVE_MERCHANT';
export const DEDUCTION_INTEGRAL = 'DEDUCTION_INTEGRAL';

export const UPDATE_NEWS_NOT_READ = 'UPDATE_NEWS_NOT_READ';

export const UPDATE_INTEGRAL = 'UPDATE_INTEGRAL';




